config/routes.rb
Salami::Application.routes.draw do
  devise_for :users

  get "home/index"
  match 'admin' => 'admin#index'
  match 'admin/:id/become' => 'admin#become'

   root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  default_scope order('email')

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  before_filter :authenticate_user!, :only => :token
  before_filter :is_admin

  def index
  	if params.has_key?(:search)
  	  if params.has_key?(:page)
  	    @users = User.where("email like ?", "%#{params[:search]}%").page(params[:page]).per(10)
  	    @count = User.where("email like ?", "%#{params[:search]}%").count
  	  else
  	    @users = User.where("email like ?", "%#{params[:search]}%").page(1).per(10)
  	    @count = User.where("email like ?", "%#{params[:search]}%").count
  	  end
  	else
  	  @users = User.page(params[:page]).per(10)
  	  @count = User.count
  	end
  end

  def is_admin
  	if not current_user.try(:admin?)
  		flash[:alert] = 'Your account does not have administrative privileges.'
  		redirect_to :controller => "home", :action => "index"
  	end
  	return true
  end

  def become
    sign_in(:user, User.find(params[:id]))
    redirect_to root_url # or user_root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def resource_name
		:user
	end

	def resource
		@resource ||= User.new
	end

	def devise_mapping
		@devise_mapping ||= Devise.mappings[:user]
	end
	
	def nav_link(link_text, link_path)
	  class_name = current_page?(link_path) ? 'active' : ''
	  content_tag(:li, :class => class_name) do
	    link_to link_text, link_path
	  end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/index.html.erb
<h2>Manage User Accounts</h2><br />
<!-- Postfix action -->
<div class="row collapse five columns">
  <div class="ten mobile-three columns">
  <% if params.has_key?(:search) and params[:search] != "" %>

  <%= form_for "/admin" do %>
    <%= text_field_tag :search, params[:search] %>
  </div>
  <div class="two mobile-one columns">
    <%= submit_tag "Search", :class => "button postfix" %>
  <% end %>
	<%= form_for "/admin" do %>
	    <%= text_field_tag :search, "", :style => "display: none;" %>
	    <%= submit_tag "Clear", :class => "secondary button postfix" %>
	<% end %>
  <% else %>

    <%= form_for "/admin" do %>
    <%= text_field_tag :search, params[:search] %>
  </div>
  <div class="two mobile-one columns">
    <%= submit_tag "Search", :class => "button postfix" %>
  <% end %>
  <% end %>
  </div>
  <div class="two mobile-one columns">
  	<span class="secondary label">Total Results: <%= @count %></span>
  </div>
</div>


<div class="row">
    <div class="twelve columns">
      <%= paginate @users, :params => {:search => params[:search]} %>
    	<table class="twelve">
    	  <thead>
		    <tr>
		      <th>Email</th>
		      <th>Sign Up Date</th>
		      <th>Time Since Last Login</th>
		      <th>Sign In Count</th>
		      <th>Is an admin account?</th>
		      <th>Login As User</th>
		    </tr>
		  </thead>
		  <tbody>
	        <% @users.each do |a| %>
		    <tr>
	          <td><%= a.email %></td>
	          <td><%= a.created_at %></td>
	          <td>Days:<%= ((Time.now - a.last_sign_in_at).to_i / 86400) % 86400 %> Hours:<%= ((Time.now - a.last_sign_in_at).to_i / 3600)%3600 %> Minutes:<%= ((Time.now - a.last_sign_in_at).to_i / 60) %60 %></td>
	          <td><%= a.sign_in_count %></td>
	          <td><%= a.admin? ? 'yes' : 'no' %></td>
	          <td><%= link_to 'Login', "/admin/#{a.id}/become", :class => 'button' %></td>
		    </tr>
		   <% end %>
		  </tbody>
		</table>
      <%= paginate @users, :params => {:search => params[:search]} %>
    </div>
	<hr />
</div>

app/views/home/index.html.erb
    <!-- Content Slider -->
 
    <div class="row">
      <div class="twelve columns hide-for-small">
        <div id="featured">
          <img src="http://placehold.it/1200x500&text=1200x500 Slide Image 1" alt="slide image">
          <img src="http://placehold.it/1200x500&text=1200x500 Slide Image 2" alt="slide image">
          <img src="http://placehold.it/1200x500&text=1200x500 Slide Image 3" alt="slide image">
        </div>
      <hr />
      </div>
    </div>
 
    <!-- End Content Slider -->
 
    <!-- Mobile Header -->
 
      <div class="row">
        <div class="twelve columns show-for-small">
          <img src="http://placehold.it/1200x700&text=Mobile Header">
        </div>
      </div>
 
    <!-- End Mobile Header -->
 
 
    <!-- Second Band (Image Left with Text) -->
  
  <div class="row">
    <div class="twelve columns">
      <div class="row">
        <div class="seven columns">
          <h4>This is a content section.</h4>
          <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef. Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef. Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
        </div>
        <div class="five columns">
          <%= render "devise/registrations/new" %>
        </div>
      </div>
    </div>
  </div>
  
  
  <!-- Third Band (Image Right with Text) -->
  
  <div class="row">
    <div class="four columns">
     <div class="flex-video">
        <img src="http://placehold.it/400x300&text=[Youtube Video]" />
        <!-- <iframe width="420" height="315" src="http://www.youtube.com/embed/9otNWTHOJi8" frameborder="0" allowfullscreen></iframe> -->
      </div>
    </div>


    <div class="eight columns">
      <h4>This is a content section.</h4>
      
      <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
      
      <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Title</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width"/>
</head>
<body>
	<!-- Navigation -->
	<div class="fixed contain-to-grid">
	<nav class="top-bar">
    <ul>
      <li class="name"><h1><%=link_to "Salami", root_path() %></h1></li>
      <li class="toggle-topbar"><a href="#"></a></li>
    </ul>
 
    <section>
      <ul class="left">
        <%= nav_link "Home", root_path %>
        <% if current_user.try(:admin?) %>
          <%= nav_link "Admin", admin_path %>
        <% end %>
      </ul>
      <% if user_signed_in? %>
      <ul class="right">
        
        <li class="has-dropdown">
          <%= link_to "Profile", edit_user_registration_path %>
 
          <ul class="dropdown">
            <%= nav_link 'Edit', edit_user_registration_path %>
            <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li> -->
      </ul>
      <% else %>
	      <%= render "devise/sessions/new" %>
      <% end %>
    </section>
  </nav>
</div>
  <!-- End Navigation -->

   <br />
   <div class="row">
   	    <% if notice %>
      <div class="alert-box success">
        <%= notice %>
        <a href="" class="close">&times;</a>
      </div>
    <% end %>
    <% if alert %>
      <div class="alert-box alert">
        <%= alert %>
        <a href="" class="close">&times;</a>
      </div>
    <% end %>
    <div class="twelve columns">
      <br />
      <%= yield %>

      <!-- Footer -->
      <footer class="row">
        <div class="twelve columns"><hr />
            <div class="row">
 
              <div class="six columns">
                  <p>&copy; Copywrite No one at all.</p>
              </div> 
            </div>
        </div>
      </footer>
      <!-- End Footer -->
      
      </div>
    </div>
  </body>
</html>